access-token:
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}

refresh-token:
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}